name: CI

on: 
  pull_request:
    branches:
    - master
    

jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:stable

    steps:
    - uses: actions/checkout@v1
    - run: flutter pub get
    - run: flutter analyze --suppress-analytics
