name: CI

on: 
  pull_request:
    branches:
    - master
    

jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:stable

    steps:
    - uses: actions/checkout@v1
    - run: sudo chown -R cirrus:cirrus /github/home/
    - name: Flutter analyze --suppress-analytics
      run: flutter analyze
